<?php

namespace AppBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByIdQuery(int $id)
    {
        $query = $this->_em->createQuery("SELECT i FROM AppBundle:Item i WHERE i.id = :id");
        $query->setParameter('id', $id);

        return $query;
    }

    public function findAllQuery()
    {
        return $this->_em->createQuery("SELECT i FROM AppBundle:Item i");
    }
    
}
